---
# This Playbook deploys ddclient 

- hosts: ddclient 
  vars_files:
    - vars/main.yml
    - vars/private.yml
  user: $global_user
  sudo: $global_use_sudo
  tasks:
    - include: tasks/main.yml

  handlers:
   - include: handlers/main.yml
